use_frameworks!

platform :ios, '13.0'
project 'BluxExample.xcodeproj', {
  'Debug-local' => :debug,
  'Release-local' => :release,
  'Debug-dev' => :debug,
  'Release-dev' => :release,
  'Debug-stg' => :debug,
  'Release-stg' => :release,
  'Debug-prod' => :debug,
  'Release-prod' => :release,
}

target 'BluxExample' do
  pod 'BluxClient', :path => '../'
end

target 'BluxNotificationServiceExtension' do
  pod 'BluxClient', :path => '../'
end
