use_frameworks!

platform :ios, '13.0'
project 'BluxExample.xcodeproj'

target 'BluxExample' do
  pod 'BluxClient', :path => '../'
end

target 'BluxNotificationServiceExtension' do
  pod 'BluxClient', :path => '../'
end
